apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "documents.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "documents.name" . }}
    helm.sh/chart: {{ include "documents.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "documents.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "documents.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}    
    spec:
      securityContext:
        runAsUser: {{ .Values.monitoring.runAsUser }}
        fsGroup: {{ .Values.monitoring.fsGroup }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}                                                             
          ports:
            - containerPort: {{ .Values.service.targetPort }}
              name: {{ .Values.service.portName }}
          resources:
{{- toYaml .Values.resources | nindent 12 }}
{{- if .Values.image.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
{{- end }}
{{- with .Values.nodeSelector }}
      nodeSelector:
{{- toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.affinity }}
      affinity:
{{- toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.tolerations }}
      tolerations:
{{- toYaml . | nindent 8 }}
{{- end }}